ALTER TABLE daily_shifts 
ADD COLUMN IF NOT EXISTS ot_hours_day NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS ot_hours_night NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS ot_hours_special NUMERIC DEFAULT 0;
